import { mysqlTable, int, varchar, datetime, date, tinyint } from "drizzle-orm/mysql-core";

export const stokMaterial = mysqlTable("stok_material", {
  no: int("no").autoincrement().primaryKey(),
  st: varchar("st", { length: 5 }),
  post_date: datetime("post_date", { mode: "string" }),
  no_kpm: varchar("no_kpm", { length: 25 }),
  item: int("item"),
  komat: varchar("komat", { length: 50 }),
  spesifikasi: varchar("spesifikasi", { length: 250 }),
  wbs: varchar("wbs", { length: 15 }),
  proyek: varchar("proyek", { length: 100 }),
  typecar: varchar("typecar", { length: 10 }),
  ts: int("ts"),
  qty: int("qty"),
  uom: varchar("uom", { length: 10 }),
  sn: varchar("sn", { length: 25 }),
  pic: varchar("pic", { length: 10 }),
  out: tinyint("out"),
  status: varchar("status", { length: 50 }),
  out_date: date("out_date", { mode: "string" }),
  tgl_ready: date("tgl_ready", { mode: "string" }),
  qty_ready: int("qty_ready"),
  status_komponen: varchar("status_komponen", { length: 15 }),
  pic_reservasi: varchar("pic_reservasi", { length: 10 }),
  no_reservasi: varchar("no_reservasi", { length: 50 }),
  dev: varchar("dev", { length: 10 }),
  stok_warehouse: int("stok_warehouse"),
  stok_ppc: int("stok_ppc"),
  stok_ijon: int("stok_ijon"),
  stok_nonval: int("stok_nonval"),
  kategori_komponen: varchar("kategori_komponen", { length: 3 }),
  lokasi_gd: varchar("lokasi_gd", { length: 50 }),
});
